apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  SPRING_DATA_MONGODB_USERNAME: {{ .Values.secret.MONGODB_USERNAME }}
  SPRING_DATA_MONGODB_PASSWORD: {{ .Values.secret.MONGODB_PASSWORD }}
  SPRING_MAIL_USERNAME: {{ .Values.secret.MAIL_USERNAME }}
  SPRING_MAIL_PASSWORD: {{ .Values.secret.MAIL_PASSWORD }}
 