apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_USER: {{ .Values.secrets.mongoUser | quote }}
  MONGO_PASS: {{ .Values.secrets.mongoPass | quote }}
  SPRING_MAIL_USERNAME: {{ .Values.secrets.springMailUsername | quote }}
  SPRING_MAIL_PASSWORD: {{  .Values.secrets.springMailPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote}}


